cc_library(
    name = "eye_features",
    srcs = ["eye.cc"],
    deps = [
        "//mediapipe/modules/face_landmark:face_landmark_front_cpu",
        "//mediapipe/framework/port:opencv_imgproc"
    ],
    alwayslink=1
)
