cc_library(
    name = "generic_analyzer",
    srcs = ["generic_analyzer.cc"],
    hdrs = ["generic_analyzer.h"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_core",
    ],
    alwayslink = 1,
)