cc_library(
    name = "mouth",
    srcs = ["mouth.cc"],
    hdrs = ["mouth.h"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//mediapipe/framework/port:opencv_core",
        "//mediapipe/framework/port:opencv_imgproc",
    ],
    alwayslink = 1,
)