cc_library(
    name = "eye",
    srcs = ["eye.cc"],
    hdrs = ["eye.h"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_core",
    ],
    alwayslink = 1,
)