# This is a basic workflow for code style checking

name: Code style analysis

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install pip
        run: apt install python3-pip

      # Runs a set of commands using the runners shell
      - name: Install tools for code style checking
        run: |
          pip install cpplint \
          pip install pycodestyle
          
      - name: Run code checking against .cc and .h files
        run: | 
          echo "Checking cpp files" \
          find src -type f \( -iname \*.cc -o -iname \*.h \) -exec cpplint {} \;
          
      - name: Run code checking against .py files
        run: |
          echo "Checking python files" \
          find src model experiments -type f -name "*.py" -exec pycodestyle {} \;
